name: book_app_themed
description: Cupertino-themed book tracker app for Android (Flutter UI without Material widgets).
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  fl_chart: ^0.69.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  archive: ^3.6.1
  share_plus: ^10.1.4
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: false
  assets:
    - assets/icons/blackpiratex_book_tracker_icon.svg
